using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ryn.Ipc.Generator;

internal static class Emitter
{
    /// <summary>
    /// Fully-qualified display form (<see cref="SymbolDisplayFormat.FullyQualifiedFormat"/>) of
    /// <c>System.Text.Json.JsonElement</c> as it appears in <see cref="CommandInfo.InnerReturnType"/>.
    /// Used for an EXACT match instead of a brittle <c>EndsWith("JsonElement")</c> heuristic that would
    /// also catch user types whose name merely ends in "JsonElement".
    /// </summary>
    private const string JsonElementFullName = "global::System.Text.Json.JsonElement";

    public static string? Emit(CommandGroup group, SourceProductionContext ctx)
    {
        if (!Validate(group, ctx))
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Ryn.Ipc;");
        sb.AppendLine();

        if (group.Namespace is not null)
        {
            sb.AppendLine($"namespace {group.Namespace};");
            sb.AppendLine();
        }

        EmitRouter(sb, group);
        sb.AppendLine();
        EmitExtensions(sb, group);

        return sb.ToString();
    }

    private static bool Validate(CommandGroup group, SourceProductionContext ctx)
    {
        var valid = true;
        var seenNames = new HashSet<string>(StringComparer.Ordinal);
        var hasJsonContext = group.JsonContextTypeFullName is not null;

        foreach (var cmd in group.Commands)
        {
            if (!cmd.IsAccessible)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MethodMustBeAccessible,
                    cmd.Location,
                    cmd.MethodName));
                valid = false;
            }

            if (!seenNames.Add(cmd.CommandName))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.DuplicateCommandName,
                    cmd.Location,
                    cmd.CommandName));
                valid = false;
            }

            if (!IsReturnTypeSupported(cmd, hasJsonContext))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.UnsupportedReturnType,
                    cmd.Location,
                    cmd.ReturnTypeDisplay));
                valid = false;
            }

            for (var i = 0; i < cmd.Parameters.Length; i++)
            {
                var p = cmd.Parameters[i];
                if (p.IsCancellationToken)
                {
                    if (i != cmd.Parameters.Length - 1)
                    {
                        ctx.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.CancellationTokenMustBeLast,
                            cmd.Location,
                            p.Name));
                        valid = false;
                    }
                }
                else if (p.IsInjected)
                {
                    // resolved from DI, not from JSON — always valid
                }
                else if (!IsParameterTypeSupported(p, hasJsonContext))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.UnsupportedParameterType,
                        cmd.Location,
                        p.Name, p.TypeDisplay));
                    valid = false;
                }
            }
        }

        return valid;
    }

    private static bool IsParameterTypeSupported(ParameterInfo p, bool hasJsonContext)
    {
        if (p.IsJsonElement)
            return true;

        if (p.IsArray)
            return IsPrimitiveSpecialType(p.ArrayElementSpecialType);

        if (p.IsNullable)
            return IsPrimitiveSpecialType(p.NullableUnderlyingSpecialType);

        // GEN-03: a nullable reference type (`string?`, `MyDto?`) is supported on the same terms as its
        // non-nullable form — a primitive (string) directly, anything else only with a JsonSerializerContext.
        if (p.IsNullableReference)
            return p.SpecialType == SpecialType.System_String || hasJsonContext;

        if (IsPrimitiveSpecialType(p.SpecialType))
            return true;

        // Non-primitive types are allowed when a JsonSerializerContext is provided
        return hasJsonContext;
    }

    private static bool IsReturnTypeSupported(CommandInfo cmd, bool hasJsonContext)
    {
        if (cmd.IsVoidReturn)
            return true;

        if (cmd.IsReturnArray)
            return IsPrimitiveSpecialType(cmd.ReturnArrayElementSpecialType);

        if (cmd.IsReturnNullable)
            return IsPrimitiveSpecialType(cmd.ReturnNullableUnderlyingSpecialType);

        if (IsPrimitiveSpecialType(cmd.InnerReturnSpecialType))
            return true;

        // A JsonElement return is serialized verbatim via GetRawText() and needs no JsonSerializerContext.
        if (cmd.InnerReturnType == JsonElementFullName)
            return true;

        // Non-primitive return types are allowed when a JsonSerializerContext is provided
        return hasJsonContext;
    }

    private static bool IsPrimitiveSpecialType(SpecialType type) =>
        type is
            SpecialType.System_Int32 or
            SpecialType.System_Int64 or
            SpecialType.System_Single or
            SpecialType.System_Double or
            SpecialType.System_Boolean or
            SpecialType.System_String or
            SpecialType.System_Byte or
            SpecialType.System_SByte or
            SpecialType.System_Int16 or
            SpecialType.System_UInt16 or
            SpecialType.System_UInt32 or
            SpecialType.System_UInt64 or
            SpecialType.System_Decimal or
            SpecialType.System_Char;

    private static void EmitRouter(StringBuilder sb, CommandGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var commandNames = string.Join(" or ", group.Commands.Select(c => $"\"{c.CommandName}\""));

        sb.AppendLine($"file sealed class {routerName} : ICommandRouter");
        sb.AppendLine("{");
        sb.AppendLine($"    public bool CanRoute(string command) => command is {commandNames};");
        sb.AppendLine();
        sb.AppendLine("    public async ValueTask<string> RouteAsync(");
        sb.AppendLine("        string command, ReadOnlyMemory<byte> args, IServiceProvider services, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (command)");
        sb.AppendLine("        {");

        foreach (var cmd in group.Commands)
        {
            EmitCase(sb, cmd, group);
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new RynCommandNotFoundException(command);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string __ToJson(string? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value is null) return \"null\";");
        sb.AppendLine("        var sb = new System.Text.StringBuilder(value.Length + 2);");
        sb.AppendLine("        sb.Append('\"');");
        sb.AppendLine("        foreach (var c in value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (c)");
        sb.AppendLine("            {");
        sb.AppendLine("                case '\\\\': sb.Append(\"\\\\\\\\\"); break;");
        sb.AppendLine("                case '\"': sb.Append(\"\\\\\\\"\"); break;");
        sb.AppendLine("                case '\\n': sb.Append(\"\\\\n\"); break;");
        sb.AppendLine("                case '\\r': sb.Append(\"\\\\r\"); break;");
        sb.AppendLine("                case '\\t': sb.Append(\"\\\\t\"); break;");
        sb.AppendLine("                case '\\b': sb.Append(\"\\\\b\"); break;");
        sb.AppendLine("                case '\\f': sb.Append(\"\\\\f\"); break;");
        sb.AppendLine("                default:");
        sb.AppendLine("                    if (c < ' ' || c == '\\u2028' || c == '\\u2029')");
        sb.AppendLine("                        sb.Append($\"\\\\u{(int)c:X4}\");");
        sb.AppendLine("                    else");
        sb.AppendLine("                        sb.Append(c);");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        sb.Append('\"');");
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitCase(StringBuilder sb, CommandInfo cmd, CommandGroup group)
    {
        sb.AppendLine($"            case \"{cmd.CommandName}\":");
        sb.AppendLine("            {");

        var jsonParams = cmd.Parameters.Where(p => !p.IsCancellationToken && !p.IsInjected).ToList();

        if (jsonParams.Count > 0)
        {
            sb.AppendLine("                using var __doc = JsonDocument.Parse(args);");
            sb.AppendLine("                var __root = __doc.RootElement;");

            for (var i = 0; i < jsonParams.Count; i++)
            {
                var p = jsonParams[i];
                var camelName = ToCamelCase(p.Name);
                EmitParameterExtraction(sb, p, i, camelName, cmd.CommandName, group.JsonContextTypeFullName);
            }
        }

        var callArgs = new StringBuilder();
        var jsonIndex = 0;
        for (var i = 0; i < cmd.Parameters.Length; i++)
        {
            if (i > 0) callArgs.Append(", ");
            var p = cmd.Parameters[i];
            if (p.IsCancellationToken)
                callArgs.Append("cancellationToken");
            else if (p.IsInjected)
                callArgs.Append(p.TypeDisplay == "global::System.IServiceProvider"
                    ? "services"
                    : $"services.GetRequiredService<{p.TypeDisplay}>()");
            else
                callArgs.Append($"__p{jsonIndex++}");
        }

        string target;
        if (cmd.IsStatic)
        {
            target = $"{group.TypeFullName}.{cmd.MethodName}";
        }
        else
        {
            sb.AppendLine($"                var __instance = services.GetRequiredService<{group.TypeFullName}>();");
            target = $"__instance.{cmd.MethodName}";
        }

        if (cmd.IsVoidReturn)
        {
            if (cmd.IsAsync)
            {
                sb.AppendLine($"                await {target}({callArgs}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"                {target}({callArgs});");
            }
            sb.AppendLine("                return \"null\";");
        }
        else
        {
            if (cmd.IsAsync)
            {
                sb.AppendLine($"                var __result = await {target}({callArgs}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"                var __result = {target}({callArgs});");
            }

            EmitResultSerializer(sb, cmd, group.JsonContextTypeFullName);
        }

        sb.AppendLine("            }");
    }

    private static void EmitParameterExtraction(
        StringBuilder sb, ParameterInfo p, int index, string camelName, string commandName, string? jsonContextType)
    {
        // Look the property up once with TryGetProperty so we can give a descriptive error when a
        // required argument is absent, instead of the opaque KeyNotFoundException GetProperty throws.
        sb.AppendLine($"                var __has{index} = __root.TryGetProperty(\"{camelName}\", out var __prop{index});");

        if (p.IsNullable)
        {
            // Nullable<T> (struct, e.g. `int?`, `double?`). Precedence mirrors the non-nullable defaulted
            // path: a present explicit JSON null always binds null; a MISSING arg binds the declared C#
            // default if one is non-null (GEN-02 for nullables), otherwise null; a present value reads
            // normally. The `(T?)` casts keep `var` inferring the Nullable<T> so it binds without a warning.
            var elementGetter = GetElementGetter(p.NullableUnderlyingSpecialType);
            var csType = GetCSharpTypeName(p.NullableUnderlyingSpecialType);

            if (p.HasDefault && p.DefaultLiteral != "null")
            {
                // A non-null Nullable<T> default (e.g. `int? count = 10`): a missing arg restores the
                // declared default instead of collapsing to null, which the old single-expression form did.
                sb.AppendLine($"                var __p{index} = !__has{index} ? ({csType}?){p.DefaultLiteral} : (__prop{index}.ValueKind == System.Text.Json.JsonValueKind.Null ? ({csType}?)null : __prop{index}{elementGetter});");
                return;
            }

            // No default (or a `= null` default, which agrees with the missing-arg behavior): a missing arg
            // or a JSON null both yield null — the only sensible value when no non-null default is declared.
            sb.AppendLine($"                var __p{index} = (!__has{index} || __prop{index}.ValueKind == System.Text.Json.JsonValueKind.Null) ? ({csType}?)null : __prop{index}{elementGetter};");
            return;
        }

        // Build the expression that reads a PRESENT, non-null property into the parameter's type. This is the
        // body that runs once the missing/null preconditions below are satisfied.
        var read = BuildReadExpression(p, index, jsonContextType);

        if (p.IsNullableReference)
        {
            // GEN-03: a nullable-annotated reference type (`string?`, `MyDto?`) accepts a missing arg or an
            // explicit JSON null as null — restoring the pre-P5 behavior. The `var` local infers the nullable
            // reference type, which binds to the (also nullable) parameter without a warning.
            sb.AppendLine($"                var __p{index} = (!__has{index} || __prop{index}.ValueKind == System.Text.Json.JsonValueKind.Null) ? null : {read};");
            return;
        }

        // A NON-nullable reference type whose C# default is null/`default` (a contradictory but legal
        // declaration — the user's own method already warns) still binds missing/explicit-null to null,
        // since that is the only value the declared default can produce. A null default literal is only ever
        // produced for a reference type, so no value-type guard is needed. The trailing `!` forgives the
        // null so the `var` local infers the non-nullable type and binds without a CS8604 warning.
        if (p.HasDefault && p.DefaultLiteral == "null")
        {
            sb.AppendLine($"                var __p{index} = ((!__has{index} || __prop{index}.ValueKind == System.Text.Json.JsonValueKind.Null) ? null : {read})!;");
            return;
        }

        // Non-nullable from here. Precedence: a present explicit null is rejected by the null guard below;
        // a MISSING arg binds the C# default literal if one exists (GEN-02), otherwise throws.
        if (p.HasDefault)
        {
            // JsonElement parameters never reach here: a JsonElement default is not expressible in C#, so
            // HasExplicitDefaultValue is only ever true for the value/string/complex kinds handled by read.
            EmitNullArgGuardForPresent(sb, p, index, camelName, commandName);
            sb.AppendLine($"                var __p{index} = !__has{index} ? {p.DefaultLiteral} : {read};");
            return;
        }

        // No default: a missing arg is an error.
        EmitMissingArgGuard(sb, index, camelName, commandName);
        EmitNullArgGuardForPresent(sb, p, index, camelName, commandName);
        sb.AppendLine($"                var __p{index} = {read};");
    }

    /// <summary>
    /// Builds the C# expression that reads a present, non-null <c>__prop{index}</c> into the parameter's
    /// type. Shared by the nullable-reference, defaulted, and required binding paths so the read logic for
    /// each supported kind lives in exactly one place.
    /// </summary>
    private static string BuildReadExpression(ParameterInfo p, int index, string? jsonContextType)
    {
        if (p.IsJsonElement)
            return $"__prop{index}";

        if (p.IsArray)
        {
            var elementGetter = GetElementGetter(p.ArrayElementSpecialType);
            return $"__prop{index}.EnumerateArray().Select(e => e{elementGetter}).ToArray()";
        }

        if (p.SpecialType == SpecialType.System_String)
            return $"__prop{index}.GetString()!";

        if (p.SpecialType == SpecialType.System_Char)
            return $"__prop{index}.GetString()![0]";

        if (IsPrimitiveSpecialType(p.SpecialType))
            return $"__prop{index}{GetElementGetter(p.SpecialType)}";

        if (jsonContextType is not null)
        {
            // Complex type — deserialized straight from the JsonElement (no GetRawText() string round-trip).
            var typeInfoProp = GetTypeInfoPropertyName(p.TypeDisplay);
            return $"JsonSerializer.Deserialize(__prop{index}, {jsonContextType}.Default.{typeInfoProp})!";
        }

        // Fallback: should not reach here if validation passed.
        return $"__prop{index}{GetElementGetter(p.SpecialType)}";
    }

    /// <summary>
    /// Emits the "must not be JSON null" guard for the non-nullable kinds that would otherwise dereference a
    /// null (string/char/array/complex). Primitive value types and JsonElement do not need it.
    /// </summary>
    private static void EmitNullArgGuardForPresent(
        StringBuilder sb, ParameterInfo p, int index, string camelName, string commandName)
    {
        var needsNullGuard = p.IsArray
            || p.SpecialType == SpecialType.System_String
            || p.SpecialType == SpecialType.System_Char
            || (!p.IsJsonElement && !IsPrimitiveSpecialType(p.SpecialType));
        if (needsNullGuard)
            EmitNullArgGuard(sb, index, camelName, commandName);
    }

    /// <summary>Emits a guard that throws a descriptive error when a required argument is absent from the JSON.</summary>
    private static void EmitMissingArgGuard(StringBuilder sb, int index, string camelName, string commandName)
    {
        sb.AppendLine($"                if (!__has{index})");
        sb.AppendLine($"                    throw new RynIpcArgumentException(\"{commandName}\", \"{camelName}\", \"required argument is missing\");");
    }

    /// <summary>Emits a guard that throws a descriptive error when a non-nullable argument is JSON null.</summary>
    private static void EmitNullArgGuard(StringBuilder sb, int index, string camelName, string commandName)
    {
        sb.AppendLine($"                if (__prop{index}.ValueKind == System.Text.Json.JsonValueKind.Null)");
        sb.AppendLine($"                    throw new RynIpcArgumentException(\"{commandName}\", \"{camelName}\", \"argument must not be null\");");
    }

    private static string GetElementGetter(SpecialType type) => type switch
    {
        SpecialType.System_Int32 => ".GetInt32()",
        SpecialType.System_Int64 => ".GetInt64()",
        SpecialType.System_Single => ".GetSingle()",
        SpecialType.System_Double => ".GetDouble()",
        SpecialType.System_Boolean => ".GetBoolean()",
        SpecialType.System_String => ".GetString()!",
        SpecialType.System_Byte => ".GetByte()",
        SpecialType.System_SByte => ".GetSByte()",
        SpecialType.System_Int16 => ".GetInt16()",
        SpecialType.System_UInt16 => ".GetUInt16()",
        SpecialType.System_UInt32 => ".GetUInt32()",
        SpecialType.System_UInt64 => ".GetUInt64()",
        SpecialType.System_Decimal => ".GetDecimal()",
        SpecialType.System_Char => ".GetString()![0]",
        _ => ".GetRawText()",
    };

    private static string GetCSharpTypeName(SpecialType type) => type switch
    {
        SpecialType.System_Int32 => "int",
        SpecialType.System_Int64 => "long",
        SpecialType.System_Single => "float",
        SpecialType.System_Double => "double",
        SpecialType.System_Boolean => "bool",
        SpecialType.System_String => "string",
        SpecialType.System_Byte => "byte",
        SpecialType.System_SByte => "sbyte",
        SpecialType.System_Int16 => "short",
        SpecialType.System_UInt16 => "ushort",
        SpecialType.System_UInt32 => "uint",
        SpecialType.System_UInt64 => "ulong",
        SpecialType.System_Decimal => "decimal",
        SpecialType.System_Char => "char",
        _ => "object",
    };

    private static void EmitResultSerializer(StringBuilder sb, CommandInfo cmd, string? jsonContextType)
    {
        if (cmd.IsReturnArray)
        {
            sb.AppendLine("                if (__result is null) return \"null\";");
            EmitArraySerializer(sb, cmd.ReturnArrayElementSpecialType);
        }
        else if (cmd.IsReturnNullable)
        {
            if (cmd.ReturnNullableUnderlyingSpecialType == SpecialType.System_String)
            {
                // string? is a reference type nullable — just call __ToJson which handles null
                sb.AppendLine("                return __ToJson(__result);");
            }
            else
            {
                var innerSerializer = GetScalarSerializer("__result.Value", cmd.ReturnNullableUnderlyingSpecialType);
                sb.AppendLine($"                return __result.HasValue ? {innerSerializer} : \"null\";");
            }
        }
        else if (IsPrimitiveSpecialType(cmd.InnerReturnSpecialType))
        {
            var serializer = GetScalarSerializer("__result", cmd.InnerReturnSpecialType);
            sb.AppendLine($"                return {serializer};");
        }
        else if (cmd.InnerReturnType == JsonElementFullName)
        {
            sb.AppendLine("                return __result.GetRawText();");
        }
        else if (jsonContextType is not null)
        {
            // Complex return type — serialize via the user-supplied JsonSerializerContext
            var typeInfoProp = GetTypeInfoPropertyName(cmd.InnerReturnType);
            sb.AppendLine($"                return JsonSerializer.Serialize(__result, {jsonContextType}.Default.{typeInfoProp});");
        }
        else
        {
            var serializer = GetScalarSerializer("__result", cmd.InnerReturnSpecialType);
            sb.AppendLine($"                return {serializer};");
        }
    }

    private static string GetScalarSerializer(string varName, SpecialType type) => type switch
    {
        // Non-finite floats (NaN/±Infinity) are NOT valid JSON; emit `null` to match JSON.stringify
        // rather than a bare token the bridge would silently deliver as a corrupt string.
        SpecialType.System_Single or SpecialType.System_Double =>
            $"(double.IsFinite({varName}) ? {varName}.ToString(System.Globalization.CultureInfo.InvariantCulture) : \"null\")",
        SpecialType.System_Int32 or SpecialType.System_Int64 or SpecialType.System_Byte or
        SpecialType.System_SByte or SpecialType.System_Int16 or SpecialType.System_UInt16 or
        SpecialType.System_UInt32 or SpecialType.System_UInt64 or SpecialType.System_Decimal =>
            $"{varName}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Boolean => $"{varName} ? \"true\" : \"false\"",
        SpecialType.System_String => $"__ToJson({varName})",
        SpecialType.System_Char => $"__ToJson({varName}.ToString())",
        _ => $"{varName}.ToString()",
    };

    private static void EmitArraySerializer(StringBuilder sb, SpecialType elementType)
    {
        sb.AppendLine("                var __sb = new System.Text.StringBuilder(\"[\");");
        sb.AppendLine("                for (var __i = 0; __i < __result.Length; __i++)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (__i > 0) __sb.Append(',');");

        if (elementType == SpecialType.System_String)
        {
            sb.AppendLine("                    __sb.Append(__ToJson(__result[__i]));");
        }
        else if (elementType == SpecialType.System_Char)
        {
            sb.AppendLine("                    __sb.Append(__ToJson(__result[__i].ToString()));");
        }
        else if (elementType == SpecialType.System_Boolean)
        {
            sb.AppendLine("                    __sb.Append(__result[__i] ? \"true\" : \"false\");");
        }
        else if (elementType is SpecialType.System_Single or SpecialType.System_Double)
        {
            // Non-finite floats (NaN/±Infinity) are not valid JSON — emit `null` to match JSON.stringify.
            sb.AppendLine("                    __sb.Append(double.IsFinite(__result[__i]) ? __result[__i].ToString(System.Globalization.CultureInfo.InvariantCulture) : \"null\");");
        }
        else
        {
            sb.AppendLine("                    __sb.Append(__result[__i].ToString(System.Globalization.CultureInfo.InvariantCulture));");
        }

        sb.AppendLine("                }");
        sb.AppendLine("                __sb.Append(']');");
        sb.AppendLine("                return __sb.ToString();");
    }

    private static void EmitExtensions(StringBuilder sb, CommandGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var extensionName = $"{group.TypeName}RynExtensions";

        sb.AppendLine($"public static class {extensionName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection Add{group.TypeName}(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddSingleton<ICommandRouter, {routerName}>();");

        // Register non-static containing types for DI resolution
        if (group.Commands.Any(c => !c.IsStatic))
        {
            sb.AppendLine($"        services.AddSingleton<{group.TypeFullName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    /// <summary>
    /// Derives the source-generated JsonTypeInfo property name from a fully qualified type display string,
    /// mirroring System.Text.Json's naming so that generics/arrays/nested types produce a VALID identifier
    /// (the old code turned "List&lt;MyDto&gt;" into "MyDto>", which would not compile).
    /// Examples: "global::App.MyDto" -> "MyDto", "MyDto[]" -> "MyDtoArray",
    /// "System.Collections.Generic.List&lt;App.MyDto&gt;" -> "ListMyDto".
    /// </summary>
    internal static string GetTypeInfoPropertyName(string typeDisplay)
    {
        // Arrays: STJ names them "<ElementSimpleName>Array".
        var trimmed = typeDisplay.Trim();
        if (trimmed.EndsWith("[]", StringComparison.Ordinal))
            return GetTypeInfoPropertyName(trimmed.Substring(0, trimmed.Length - 2)) + "Array";

        // Generics: build "<OuterSimpleName><Arg1SimpleName><Arg2SimpleName>...".
        var lt = trimmed.IndexOf('<');
        if (lt >= 0 && trimmed.EndsWith(">", StringComparison.Ordinal))
        {
            var outer = SimpleName(trimmed.Substring(0, lt));
            var argsText = trimmed.Substring(lt + 1, trimmed.Length - lt - 2);
            var sb = new StringBuilder(outer);
            foreach (var arg in SplitGenericArgs(argsText))
                sb.Append(GetTypeInfoPropertyName(arg));
            return sb.ToString();
        }

        return SimpleName(trimmed);
    }

    private static string SimpleName(string typeDisplay)
    {
        var name = typeDisplay.Trim();
        if (name.StartsWith("global::", StringComparison.Ordinal))
            name = name.Substring("global::".Length);

        var lastDot = name.LastIndexOf('.');
        if (lastDot >= 0)
            name = name.Substring(lastDot + 1);

        // FullyQualifiedFormat renders primitives as C# keywords ("string", "int"), but STJ's
        // JsonSerializerContext derives JsonTypeInfo property names from the CLR metadata simple name
        // ("String", "Int32"). Map keyword forms back so e.g. List<string> -> "ListString" (not "Liststring")
        // and Dictionary<string,int> -> "DictionaryStringInt32", matching the generated context.
        return KeywordToMetadataName(name);
    }

    /// <summary>
    /// Maps a C# primitive keyword to its CLR metadata simple name (the form System.Text.Json uses for
    /// generated <c>JsonTypeInfo</c> property names). Non-keyword type names pass through unchanged.
    /// </summary>
    private static string KeywordToMetadataName(string name) => name switch
    {
        "bool" => "Boolean",
        "byte" => "Byte",
        "sbyte" => "SByte",
        "char" => "Char",
        "decimal" => "Decimal",
        "double" => "Double",
        "float" => "Single",
        "int" => "Int32",
        "uint" => "UInt32",
        "long" => "Int64",
        "ulong" => "UInt64",
        "short" => "Int16",
        "ushort" => "UInt16",
        "object" => "Object",
        "string" => "String",
        "nint" => "IntPtr",
        "nuint" => "UIntPtr",
        _ => name,
    };

    private static IEnumerable<string> SplitGenericArgs(string argsText)
    {
        var depth = 0;
        var start = 0;
        for (var i = 0; i < argsText.Length; i++)
        {
            var c = argsText[i];
            if (c == '<') depth++;
            else if (c == '>') depth--;
            else if (c == ',' && depth == 0)
            {
                yield return argsText.Substring(start, i - start);
                start = i + 1;
            }
        }
        yield return argsText.Substring(start);
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
