using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ryn.Ipc.Generator;

internal static class Emitter
{
    public static string? Emit(CommandGroup group, SourceProductionContext ctx)
    {
        if (!Validate(group, ctx))
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Ryn.Ipc;");
        sb.AppendLine();

        if (group.Namespace is not null)
        {
            sb.AppendLine($"namespace {group.Namespace};");
            sb.AppendLine();
        }

        EmitRouter(sb, group);
        sb.AppendLine();
        EmitExtensions(sb, group);

        return sb.ToString();
    }

    private static bool Validate(CommandGroup group, SourceProductionContext ctx)
    {
        var valid = true;
        var seenNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var cmd in group.Commands)
        {
            if (!cmd.IsAccessible)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MethodMustBeAccessible,
                    cmd.Location,
                    cmd.MethodName));
                valid = false;
            }

            if (!seenNames.Add(cmd.CommandName))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.DuplicateCommandName,
                    cmd.Location,
                    cmd.CommandName));
                valid = false;
            }

            if (!IsReturnTypeSupported(cmd))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.UnsupportedReturnType,
                    cmd.Location,
                    cmd.ReturnTypeDisplay));
                valid = false;
            }

            for (var i = 0; i < cmd.Parameters.Length; i++)
            {
                var p = cmd.Parameters[i];
                if (p.IsCancellationToken)
                {
                    if (i != cmd.Parameters.Length - 1)
                    {
                        ctx.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.CancellationTokenMustBeLast,
                            cmd.Location,
                            p.Name));
                        valid = false;
                    }
                }
                else if (!IsParameterTypeSupported(p))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.UnsupportedParameterType,
                        cmd.Location,
                        p.Name, p.TypeDisplay));
                    valid = false;
                }
            }
        }

        return valid;
    }

    private static bool IsParameterTypeSupported(ParameterInfo p) =>
        p.SpecialType is
            SpecialType.System_Int32 or
            SpecialType.System_Int64 or
            SpecialType.System_Single or
            SpecialType.System_Double or
            SpecialType.System_Boolean or
            SpecialType.System_String;

    private static bool IsReturnTypeSupported(CommandInfo cmd)
    {
        if (cmd.IsVoidReturn)
            return true;

        return cmd.InnerReturnSpecialType is
            SpecialType.System_Int32 or
            SpecialType.System_Int64 or
            SpecialType.System_Single or
            SpecialType.System_Double or
            SpecialType.System_Boolean or
            SpecialType.System_String;
    }

    private static void EmitRouter(StringBuilder sb, CommandGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var commandNames = string.Join(" or ", group.Commands.Select(c => $"\"{c.CommandName}\""));

        sb.AppendLine($"file sealed class {routerName} : ICommandRouter");
        sb.AppendLine("{");
        sb.AppendLine($"    public bool CanRoute(string command) => command is {commandNames};");
        sb.AppendLine();
        sb.AppendLine("    public async ValueTask<string> RouteAsync(");
        sb.AppendLine("        string command, ReadOnlyMemory<byte> args, IServiceProvider services, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (command)");
        sb.AppendLine("        {");

        foreach (var cmd in group.Commands)
        {
            EmitCase(sb, cmd, group);
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new RynCommandNotFoundException(command);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string __ToJson(string value) =>");
        sb.AppendLine("        \"\\\"\" + value.Replace(\"\\\\\", \"\\\\\\\\\", System.StringComparison.Ordinal).Replace(\"\\\"\", \"\\\\\\\"\", System.StringComparison.Ordinal) + \"\\\"\";");
        sb.AppendLine("}");
    }

    private static void EmitCase(StringBuilder sb, CommandInfo cmd, CommandGroup group)
    {
        sb.AppendLine($"            case \"{cmd.CommandName}\":");
        sb.AppendLine("            {");

        var jsonParams = cmd.Parameters.Where(p => !p.IsCancellationToken).ToList();
        var hasCancellation = cmd.Parameters.Any(p => p.IsCancellationToken);

        if (jsonParams.Count > 0)
        {
            sb.AppendLine("                using var __doc = JsonDocument.Parse(args);");
            sb.AppendLine("                var __root = __doc.RootElement;");

            for (var i = 0; i < jsonParams.Count; i++)
            {
                var p = jsonParams[i];
                var getter = GetJsonGetter(p);
                var camelName = ToCamelCase(p.Name);
                sb.AppendLine($"                var __p{i} = __root.GetProperty(\"{camelName}\"){getter};");
            }
        }

        var callArgs = new StringBuilder();
        var paramIndex = 0;
        for (var i = 0; i < cmd.Parameters.Length; i++)
        {
            if (i > 0) callArgs.Append(", ");
            if (cmd.Parameters[i].IsCancellationToken)
            {
                callArgs.Append("cancellationToken");
            }
            else
            {
                callArgs.Append($"__p{paramIndex++}");
            }
        }

        string target;
        if (cmd.IsStatic)
        {
            target = $"{group.TypeFullName}.{cmd.MethodName}";
        }
        else
        {
            sb.AppendLine($"                var __instance = services.GetRequiredService<{group.TypeFullName}>();");
            target = $"__instance.{cmd.MethodName}";
        }

        if (cmd.IsVoidReturn)
        {
            if (cmd.IsAsync)
            {
                sb.AppendLine($"                await {target}({callArgs}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"                {target}({callArgs});");
            }
            sb.AppendLine("                return \"null\";");
        }
        else
        {
            if (cmd.IsAsync)
            {
                sb.AppendLine($"                var __result = await {target}({callArgs}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"                var __result = {target}({callArgs});");
            }

            var serializer = GetResultSerializer(cmd);
            sb.AppendLine($"                return {serializer};");
        }

        sb.AppendLine("            }");
    }

    private static string GetJsonGetter(ParameterInfo p) => p.SpecialType switch
    {
        SpecialType.System_Int32 => ".GetInt32()",
        SpecialType.System_Int64 => ".GetInt64()",
        SpecialType.System_Single => ".GetSingle()",
        SpecialType.System_Double => ".GetDouble()",
        SpecialType.System_Boolean => ".GetBoolean()",
        SpecialType.System_String => ".GetString()!",
        _ => ".GetRawText()",
    };

    private static string GetResultSerializer(CommandInfo cmd) => cmd.InnerReturnSpecialType switch
    {
        SpecialType.System_Int32 => "__result.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Int64 => "__result.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Single => "__result.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Double => "__result.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Boolean => "__result ? \"true\" : \"false\"",
        SpecialType.System_String => "__ToJson(__result)",
        _ => "__result.ToString()",
    };

    private static void EmitExtensions(StringBuilder sb, CommandGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var extensionName = $"{group.TypeName}RynExtensions";

        sb.AppendLine($"public static class {extensionName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection Add{group.TypeName}(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddSingleton<ICommandRouter, {routerName}>();");

        // Register non-static containing types for DI resolution
        if (group.Commands.Any(c => !c.IsStatic))
        {
            sb.AppendLine($"        services.AddSingleton<{group.TypeFullName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
