using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ryn.Ipc.Generator;

internal static class Emitter
{
    public static string? Emit(CommandGroup group, SourceProductionContext ctx)
    {
        if (!Validate(group, ctx))
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Ryn.Ipc;");
        sb.AppendLine();

        if (group.Namespace is not null)
        {
            sb.AppendLine($"namespace {group.Namespace};");
            sb.AppendLine();
        }

        EmitRouter(sb, group);
        sb.AppendLine();
        EmitExtensions(sb, group);

        return sb.ToString();
    }

    private static bool Validate(CommandGroup group, SourceProductionContext ctx)
    {
        var valid = true;
        var seenNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var cmd in group.Commands)
        {
            if (!cmd.IsAccessible)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MethodMustBeAccessible,
                    cmd.Location,
                    cmd.MethodName));
                valid = false;
            }

            if (!seenNames.Add(cmd.CommandName))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.DuplicateCommandName,
                    cmd.Location,
                    cmd.CommandName));
                valid = false;
            }

            if (!IsReturnTypeSupported(cmd))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.UnsupportedReturnType,
                    cmd.Location,
                    cmd.ReturnTypeDisplay));
                valid = false;
            }

            for (var i = 0; i < cmd.Parameters.Length; i++)
            {
                var p = cmd.Parameters[i];
                if (p.IsCancellationToken)
                {
                    if (i != cmd.Parameters.Length - 1)
                    {
                        ctx.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.CancellationTokenMustBeLast,
                            cmd.Location,
                            p.Name));
                        valid = false;
                    }
                }
                else if (!IsParameterTypeSupported(p))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.UnsupportedParameterType,
                        cmd.Location,
                        p.Name, p.TypeDisplay));
                    valid = false;
                }
            }
        }

        return valid;
    }

    private static bool IsParameterTypeSupported(ParameterInfo p)
    {
        if (p.IsJsonElement)
            return true;

        if (p.IsArray)
            return IsPrimitiveSpecialType(p.ArrayElementSpecialType);

        if (p.IsNullable)
            return IsPrimitiveSpecialType(p.NullableUnderlyingSpecialType);

        return IsPrimitiveSpecialType(p.SpecialType);
    }

    private static bool IsReturnTypeSupported(CommandInfo cmd)
    {
        if (cmd.IsVoidReturn)
            return true;

        if (cmd.IsReturnArray)
            return IsPrimitiveSpecialType(cmd.ReturnArrayElementSpecialType);

        if (cmd.IsReturnNullable)
            return IsPrimitiveSpecialType(cmd.ReturnNullableUnderlyingSpecialType);

        return IsPrimitiveSpecialType(cmd.InnerReturnSpecialType);
    }

    private static bool IsPrimitiveSpecialType(SpecialType type) =>
        type is
            SpecialType.System_Int32 or
            SpecialType.System_Int64 or
            SpecialType.System_Single or
            SpecialType.System_Double or
            SpecialType.System_Boolean or
            SpecialType.System_String;

    private static void EmitRouter(StringBuilder sb, CommandGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var commandNames = string.Join(" or ", group.Commands.Select(c => $"\"{c.CommandName}\""));

        sb.AppendLine($"file sealed class {routerName} : ICommandRouter");
        sb.AppendLine("{");
        sb.AppendLine($"    public bool CanRoute(string command) => command is {commandNames};");
        sb.AppendLine();
        sb.AppendLine("    public async ValueTask<string> RouteAsync(");
        sb.AppendLine("        string command, ReadOnlyMemory<byte> args, IServiceProvider services, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (command)");
        sb.AppendLine("        {");

        foreach (var cmd in group.Commands)
        {
            EmitCase(sb, cmd, group);
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new RynCommandNotFoundException(command);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string __ToJson(string? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value is null) return \"null\";");
        sb.AppendLine("        var sb = new System.Text.StringBuilder(value.Length + 2);");
        sb.AppendLine("        sb.Append('\"');");
        sb.AppendLine("        foreach (var c in value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (c)");
        sb.AppendLine("            {");
        sb.AppendLine("                case '\\\\': sb.Append(\"\\\\\\\\\"); break;");
        sb.AppendLine("                case '\"': sb.Append(\"\\\\\\\"\"); break;");
        sb.AppendLine("                case '\\n': sb.Append(\"\\\\n\"); break;");
        sb.AppendLine("                case '\\r': sb.Append(\"\\\\r\"); break;");
        sb.AppendLine("                case '\\t': sb.Append(\"\\\\t\"); break;");
        sb.AppendLine("                case '\\b': sb.Append(\"\\\\b\"); break;");
        sb.AppendLine("                case '\\f': sb.Append(\"\\\\f\"); break;");
        sb.AppendLine("                default:");
        sb.AppendLine("                    if (c < ' ' || c == '\\u2028' || c == '\\u2029')");
        sb.AppendLine("                        sb.Append($\"\\\\u{(int)c:X4}\");");
        sb.AppendLine("                    else");
        sb.AppendLine("                        sb.Append(c);");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        sb.Append('\"');");
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitCase(StringBuilder sb, CommandInfo cmd, CommandGroup group)
    {
        sb.AppendLine($"            case \"{cmd.CommandName}\":");
        sb.AppendLine("            {");

        var jsonParams = cmd.Parameters.Where(p => !p.IsCancellationToken).ToList();
        var hasCancellation = cmd.Parameters.Any(p => p.IsCancellationToken);

        if (jsonParams.Count > 0)
        {
            sb.AppendLine("                using var __doc = JsonDocument.Parse(args);");
            sb.AppendLine("                var __root = __doc.RootElement;");

            for (var i = 0; i < jsonParams.Count; i++)
            {
                var p = jsonParams[i];
                var camelName = ToCamelCase(p.Name);
                EmitParameterExtraction(sb, p, i, camelName);
            }
        }

        var callArgs = new StringBuilder();
        var paramIndex = 0;
        for (var i = 0; i < cmd.Parameters.Length; i++)
        {
            if (i > 0) callArgs.Append(", ");
            if (cmd.Parameters[i].IsCancellationToken)
            {
                callArgs.Append("cancellationToken");
            }
            else
            {
                callArgs.Append($"__p{paramIndex++}");
            }
        }

        string target;
        if (cmd.IsStatic)
        {
            target = $"{group.TypeFullName}.{cmd.MethodName}";
        }
        else
        {
            sb.AppendLine($"                var __instance = services.GetRequiredService<{group.TypeFullName}>();");
            target = $"__instance.{cmd.MethodName}";
        }

        if (cmd.IsVoidReturn)
        {
            if (cmd.IsAsync)
            {
                sb.AppendLine($"                await {target}({callArgs}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"                {target}({callArgs});");
            }
            sb.AppendLine("                return \"null\";");
        }
        else
        {
            if (cmd.IsAsync)
            {
                sb.AppendLine($"                var __result = await {target}({callArgs}).ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"                var __result = {target}({callArgs});");
            }

            EmitResultSerializer(sb, cmd);
        }

        sb.AppendLine("            }");
    }

    private static void EmitParameterExtraction(StringBuilder sb, ParameterInfo p, int index, string camelName)
    {
        if (p.IsJsonElement)
        {
            sb.AppendLine($"                var __p{index} = __root.GetProperty(\"{camelName}\");");
        }
        else if (p.IsArray)
        {
            var elementGetter = GetElementGetter(p.ArrayElementSpecialType);
            sb.AppendLine($"                var __p{index} = __root.GetProperty(\"{camelName}\").EnumerateArray().Select(e => e{elementGetter}).ToArray();");
        }
        else if (p.IsNullable)
        {
            var elementGetter = GetElementGetter(p.NullableUnderlyingSpecialType);
            var csType = GetCSharpTypeName(p.NullableUnderlyingSpecialType);
            sb.AppendLine($"                var __prop{index} = __root.GetProperty(\"{camelName}\");");
            sb.AppendLine($"                var __p{index} = __prop{index}.ValueKind == System.Text.Json.JsonValueKind.Null ? ({csType}?)null : __prop{index}{elementGetter};");
        }
        else
        {
            var getter = GetElementGetter(p.SpecialType);
            sb.AppendLine($"                var __p{index} = __root.GetProperty(\"{camelName}\"){getter};");
        }
    }

    private static string GetElementGetter(SpecialType type) => type switch
    {
        SpecialType.System_Int32 => ".GetInt32()",
        SpecialType.System_Int64 => ".GetInt64()",
        SpecialType.System_Single => ".GetSingle()",
        SpecialType.System_Double => ".GetDouble()",
        SpecialType.System_Boolean => ".GetBoolean()",
        SpecialType.System_String => ".GetString()!",
        _ => ".GetRawText()",
    };

    private static string GetCSharpTypeName(SpecialType type) => type switch
    {
        SpecialType.System_Int32 => "int",
        SpecialType.System_Int64 => "long",
        SpecialType.System_Single => "float",
        SpecialType.System_Double => "double",
        SpecialType.System_Boolean => "bool",
        SpecialType.System_String => "string",
        _ => "object",
    };

    private static void EmitResultSerializer(StringBuilder sb, CommandInfo cmd)
    {
        if (cmd.IsReturnArray)
        {
            sb.AppendLine("                if (__result is null) return \"null\";");
            EmitArraySerializer(sb, cmd.ReturnArrayElementSpecialType);
        }
        else if (cmd.IsReturnNullable)
        {
            if (cmd.ReturnNullableUnderlyingSpecialType == SpecialType.System_String)
            {
                // string? is a reference type nullable — just call __ToJson which handles null
                sb.AppendLine("                return __ToJson(__result);");
            }
            else
            {
                var innerSerializer = GetScalarSerializer("__result.Value", cmd.ReturnNullableUnderlyingSpecialType);
                sb.AppendLine($"                return __result.HasValue ? {innerSerializer} : \"null\";");
            }
        }
        else
        {
            var serializer = GetScalarSerializer("__result", cmd.InnerReturnSpecialType);
            sb.AppendLine($"                return {serializer};");
        }
    }

    private static string GetScalarSerializer(string varName, SpecialType type) => type switch
    {
        SpecialType.System_Int32 => $"{varName}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Int64 => $"{varName}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Single => $"{varName}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Double => $"{varName}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
        SpecialType.System_Boolean => $"{varName} ? \"true\" : \"false\"",
        SpecialType.System_String => $"__ToJson({varName})",
        _ => $"{varName}.ToString()",
    };

    private static void EmitArraySerializer(StringBuilder sb, SpecialType elementType)
    {
        sb.AppendLine("                var __sb = new System.Text.StringBuilder(\"[\");");
        sb.AppendLine("                for (var __i = 0; __i < __result.Length; __i++)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (__i > 0) __sb.Append(',');");

        if (elementType == SpecialType.System_String)
        {
            sb.AppendLine("                    __sb.Append(__ToJson(__result[__i]));");
        }
        else if (elementType == SpecialType.System_Boolean)
        {
            sb.AppendLine("                    __sb.Append(__result[__i] ? \"true\" : \"false\");");
        }
        else
        {
            sb.AppendLine("                    __sb.Append(__result[__i].ToString(System.Globalization.CultureInfo.InvariantCulture));");
        }

        sb.AppendLine("                }");
        sb.AppendLine("                __sb.Append(']');");
        sb.AppendLine("                return __sb.ToString();");
    }

    private static void EmitExtensions(StringBuilder sb, CommandGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var extensionName = $"{group.TypeName}RynExtensions";

        sb.AppendLine($"public static class {extensionName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection Add{group.TypeName}(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddSingleton<ICommandRouter, {routerName}>();");

        // Register non-static containing types for DI resolution
        if (group.Commands.Any(c => !c.IsStatic))
        {
            sb.AppendLine($"        services.AddSingleton<{group.TypeFullName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
